// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Category struct {
	ID   uuid.UUID
	Name string
}

type Product struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	Description *string
	CategoryID  uuid.UUID
	IsActive    bool
	ImageUrl    *string
	Price       decimal.Decimal
	StockQty    int32
	Attributes  json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
