// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg *CreateCategoryParams) error
	CreateProduct(ctx context.Context, arg *CreateProductParams) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	GetProductByID(ctx context.Context, id uuid.UUID) (*Product, error)
	ListCategories(ctx context.Context) ([]*Category, error)
	ListProducts(ctx context.Context) ([]*Product, error)
	UpdateProduct(ctx context.Context, arg *UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
