// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg *AddOrderItemParams) error
	CreateOrder(ctx context.Context, arg *CreateOrderParams) (uuid.UUID, error)
	CreatePayment(ctx context.Context, arg *CreatePaymentParams) error
	GetActiveOrders(ctx context.Context) ([]*Order, error)
	GetAllOrders(ctx context.Context) ([]*Order, error)
	GetOrderStatus(ctx context.Context, id uuid.UUID) (*GetOrderStatusRow, error)
}

var _ Querier = (*Queries)(nil)
