// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"time"

	"github.com/google/uuid"
)

type AttributeOption struct {
	ID         int32
	CategoryID uuid.UUID
	Key        string
	Label      string
	Type       string
}

type Category struct {
	ID   uuid.UUID
	Name string
}

type User struct {
	Username       string
	HashedPassword string
	CreatedAt      time.Time
}
