// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttributeOption(ctx context.Context, arg *CreateAttributeOptionParams) error
	CreateCategory(ctx context.Context, name string) error
	DeleteAttributeOption(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	ListAttributeOptionsByCategory(ctx context.Context, categoryID uuid.UUID) ([]*AttributeOption, error)
	ListCategories(ctx context.Context) ([]*Category, error)
}

var _ Querier = (*Queries)(nil)
